-- ================================================================
-- CODEKRAFTS - FEATURE ENHANCEMENTS MIGRATION
-- ================================================================
-- This migration adds support for:
-- - Bookmarks
-- - Tags/Topics
-- - Post Drafts
-- - Post Visibility Controls
-- - Syntax Theme Preferences
-- - Post Edit Tracking
-- - View Counting
-- ================================================================

-- ================================================================
-- 1. CREATE NEW TABLES
-- ================================================================

-- Bookmarks table
CREATE TABLE IF NOT EXISTS public.bookmarks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  post_id UUID REFERENCES public.posts ON DELETE CASCADE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  UNIQUE(user_id, post_id)
);

-- Tags table
CREATE TABLE IF NOT EXISTS public.tags (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  post_count INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Post-Tags junction table
CREATE TABLE IF NOT EXISTS public.post_tags (
  post_id UUID REFERENCES public.posts ON DELETE CASCADE NOT NULL,
  tag_id BIGINT REFERENCES public.tags ON DELETE CASCADE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  PRIMARY KEY (post_id, tag_id)
);

-- ================================================================
-- 2. ALTER EXISTING TABLES
-- ================================================================

-- Add new columns to posts table
ALTER TABLE public.posts 
  ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'published' CHECK (status IN ('draft', 'published')),
  ADD COLUMN IF NOT EXISTS visibility TEXT DEFAULT 'public' CHECK (visibility IN ('public', 'followers', 'private')),
  ADD COLUMN IF NOT EXISTS edited_at TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS view_count INTEGER DEFAULT 0;

-- Add syntax theme preference to profiles
ALTER TABLE public.profiles 
  ADD COLUMN IF NOT EXISTS syntax_theme TEXT DEFAULT 'vscDarkPlus';

-- ================================================================
-- 3. CREATE INDEXES
-- ================================================================

-- Bookmarks indexes
CREATE INDEX IF NOT EXISTS idx_bookmarks_user_id ON public.bookmarks(user_id);
CREATE INDEX IF NOT EXISTS idx_bookmarks_post_id ON public.bookmarks(post_id);
CREATE INDEX IF NOT EXISTS idx_bookmarks_created_at ON public.bookmarks(created_at DESC);

-- Tags indexes
CREATE INDEX IF NOT EXISTS idx_tags_slug ON public.tags(slug);
CREATE INDEX IF NOT EXISTS idx_tags_post_count ON public.tags(post_count DESC);
CREATE INDEX IF NOT EXISTS idx_tags_name ON public.tags(name);

-- Post-Tags indexes
CREATE INDEX IF NOT EXISTS idx_post_tags_tag_id ON public.post_tags(tag_id);
CREATE INDEX IF NOT EXISTS idx_post_tags_post_id ON public.post_tags(post_id);

-- Posts indexes
CREATE INDEX IF NOT EXISTS idx_posts_status ON public.posts(status);
CREATE INDEX IF NOT EXISTS idx_posts_visibility ON public.posts(visibility);
CREATE INDEX IF NOT EXISTS idx_posts_view_count ON public.posts(view_count DESC);
CREATE INDEX IF NOT EXISTS idx_posts_edited_at ON public.posts(edited_at DESC);

-- ================================================================
-- 4. ROW LEVEL SECURITY POLICIES
-- ================================================================

-- Bookmarks policies
ALTER TABLE public.bookmarks ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view their own bookmarks" ON public.bookmarks;
CREATE POLICY "Users can view their own bookmarks"
  ON public.bookmarks FOR SELECT
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can create their own bookmarks" ON public.bookmarks;
CREATE POLICY "Users can create their own bookmarks"
  ON public.bookmarks FOR INSERT
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete their own bookmarks" ON public.bookmarks;
CREATE POLICY "Users can delete their own bookmarks"
  ON public.bookmarks FOR DELETE
  USING (auth.uid() = user_id);

-- Tags policies (public read, authenticated write)
ALTER TABLE public.tags ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Tags are viewable by everyone" ON public.tags;
CREATE POLICY "Tags are viewable by everyone"
  ON public.tags FOR SELECT
  USING (true);

DROP POLICY IF EXISTS "Authenticated users can create tags" ON public.tags;
CREATE POLICY "Authenticated users can create tags"
  ON public.tags FOR INSERT
  WITH CHECK (auth.uid() IS NOT NULL);

-- Post-Tags policies
ALTER TABLE public.post_tags ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Post tags are viewable by everyone" ON public.post_tags;
CREATE POLICY "Post tags are viewable by everyone"
  ON public.post_tags FOR SELECT
  USING (true);

DROP POLICY IF EXISTS "Users can tag their own posts" ON public.post_tags;
CREATE POLICY "Users can tag their own posts"
  ON public.post_tags FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.posts
      WHERE id = post_id AND user_id = auth.uid()
    )
  );

DROP POLICY IF EXISTS "Users can remove tags from their posts" ON public.post_tags;
CREATE POLICY "Users can remove tags from their posts"
  ON public.post_tags FOR DELETE
  USING (
    EXISTS (
      SELECT 1 FROM public.posts
      WHERE id = post_id AND user_id = auth.uid()
    )
  );

-- Update posts policies for visibility
DROP POLICY IF EXISTS "Posts are viewable by everyone" ON public.posts;
CREATE POLICY "Posts are viewable based on visibility"
  ON public.posts FOR SELECT
  USING (
    status = 'published' AND (
      visibility = 'public' 
      OR (visibility = 'followers' AND EXISTS (
        SELECT 1 FROM public.follows 
        WHERE following_id = posts.user_id AND follower_id = auth.uid()
      ))
      OR (visibility = 'private' AND user_id = auth.uid())
      OR user_id = auth.uid()
    )
  );

-- ================================================================
-- 5. DATABASE FUNCTIONS
-- ================================================================

-- Function to update tag post count
CREATE OR REPLACE FUNCTION public.update_tag_post_count()
RETURNS TRIGGER AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    UPDATE public.tags 
    SET post_count = post_count + 1 
    WHERE id = NEW.tag_id;
    RETURN NEW;
  ELSIF TG_OP = 'DELETE' THEN
    UPDATE public.tags 
    SET post_count = GREATEST(post_count - 1, 0) 
    WHERE id = OLD.tag_id;
    RETURN OLD;
  END IF;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger for tag post count
DROP TRIGGER IF EXISTS on_post_tag_change ON public.post_tags;
CREATE TRIGGER on_post_tag_change
  AFTER INSERT OR DELETE ON public.post_tags
  FOR EACH ROW EXECUTE FUNCTION public.update_tag_post_count();

-- Function to calculate trending score
CREATE OR REPLACE FUNCTION public.calculate_trending_score(
  p_likes INTEGER,
  p_comments INTEGER,
  p_age_hours NUMERIC
)
RETURNS NUMERIC AS $$
BEGIN
  RETURN (p_likes * 2 + p_comments * 3) / POWER(p_age_hours + 2, 1.5);
END;
$$ LANGUAGE plpgsql IMMUTABLE;

-- ================================================================
-- 6. VERIFICATION
-- ================================================================

-- Verify tables created
SELECT 
  table_name,
  (SELECT COUNT(*) FROM information_schema.columns WHERE table_name = t.table_name) as column_count
FROM information_schema.tables t
WHERE table_schema = 'public' 
  AND table_name IN ('bookmarks', 'tags', 'post_tags')
ORDER BY table_name;

-- Verify posts columns added
SELECT column_name, data_type, column_default
FROM information_schema.columns
WHERE table_name = 'posts' 
  AND column_name IN ('status', 'visibility', 'edited_at', 'view_count')
ORDER BY column_name;

-- Show success message
DO $$
BEGIN
  RAISE NOTICE '✅ Migration completed successfully!';
  RAISE NOTICE 'New tables: bookmarks, tags, post_tags';
  RAISE NOTICE 'Updated tables: posts (4 columns), profiles (1 column)';
  RAISE NOTICE 'Total indexes created: 14';
  RAISE NOTICE 'RLS policies: 11';
END $$;
