-- ============================================
-- REFERRAL SYSTEM SCHEMA
-- ============================================

-- 1. Referrals Table (Stores generated codes)
CREATE TABLE IF NOT EXISTS public.referrals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  referrer_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  referral_code TEXT UNIQUE NOT NULL,
  uses_count INTEGER DEFAULT 0,
  max_uses INTEGER DEFAULT 999999,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 2. Referral Uses Table (Tracks who used which code)
CREATE TABLE IF NOT EXISTS public.referral_uses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  referral_id BIGINT REFERENCES public.referrals(id) ON DELETE CASCADE NOT NULL,
  referred_user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  used_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  UNIQUE(referred_user_id) -- A user can only be referred once
);

-- 3. Indexes
CREATE INDEX IF NOT EXISTS idx_referrals_referrer_id ON public.referrals(referrer_id);
CREATE INDEX IF NOT EXISTS idx_referrals_code ON public.referrals(referral_code);
CREATE INDEX IF NOT EXISTS idx_referral_uses_referral_id ON public.referral_uses(referral_id);

-- 4. RLS Policies

-- Enable RLS
ALTER TABLE public.referrals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.referral_uses ENABLE ROW LEVEL SECURITY;

-- Referrals Policies
DROP POLICY IF EXISTS "Users can view their own referral code" ON public.referrals;
CREATE POLICY "Users can view their own referral code" 
  ON public.referrals FOR SELECT 
  USING (auth.uid() = referrer_id);

DROP POLICY IF EXISTS "Users can create their own referral code" ON public.referrals;
CREATE POLICY "Users can create their own referral code" 
  ON public.referrals FOR INSERT 
  WITH CHECK (auth.uid() = referrer_id);

-- Anyone can read referral codes to validate them during signup (public read)
-- Use a secure function or allow public read on specific columns if strict security needed.
-- For now, public read is okay for checking validity.
DROP POLICY IF EXISTS "Public can view referral codes" ON public.referrals;
CREATE POLICY "Public can view referral codes" 
  ON public.referrals FOR SELECT 
  USING (true);

-- Referral Uses Policies
DROP POLICY IF EXISTS "Users can view who they referred" ON public.referral_uses;
CREATE POLICY "Users can view who they referred" 
  ON public.referral_uses FOR SELECT 
  USING (
    EXISTS (
      SELECT 1 FROM public.referrals
      WHERE referrals.id = referral_uses.referral_id
      AND referrals.referrer_id = auth.uid()
    )
  );

-- Admins can view all
DROP POLICY IF EXISTS "Admins can view all referrals" ON public.referrals;
CREATE POLICY "Admins can view all referrals" 
  ON public.referrals FOR SELECT 
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid() AND profiles.is_admin = true
    )
  );

DROP POLICY IF EXISTS "Admins can view all referral uses" ON public.referral_uses;
CREATE POLICY "Admins can view all referral uses" 
  ON public.referral_uses FOR SELECT 
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid() AND profiles.is_admin = true
    )
  );
