-- ============================================
-- VERIFICATION REQUESTS SCHEMA FIX
-- ============================================

-- 1. Create the table if it doesn't exist, ensuring correct Foreign Key
CREATE TABLE IF NOT EXISTS public.verification_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  email TEXT, -- Capture email at time of request for notifications
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  message TEXT,
  admin_notes TEXT,
  requested_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  reviewed_at TIMESTAMP WITH TIME ZONE
);

-- 2. Add indexes for performance
CREATE INDEX IF NOT EXISTS idx_verification_requests_status ON public.verification_requests(status);
CREATE INDEX IF NOT EXISTS idx_verification_requests_user_id ON public.verification_requests(user_id);
CREATE INDEX IF NOT EXISTS idx_verification_requests_requested_at ON public.verification_requests(requested_at DESC);

-- 3. Enable RLS
ALTER TABLE public.verification_requests ENABLE ROW LEVEL SECURITY;

-- 4. RLS Policies

-- Allow users to create their own requests
DROP POLICY IF EXISTS "Users can create verification requests" ON public.verification_requests;
CREATE POLICY "Users can create verification requests" 
  ON public.verification_requests FOR INSERT 
  WITH CHECK (auth.uid() = user_id);

-- Allow users to view their own requests
DROP POLICY IF EXISTS "Users can view their own requests" ON public.verification_requests;
CREATE POLICY "Users can view their own requests" 
  ON public.verification_requests FOR SELECT 
  USING (auth.uid() = user_id);

-- Allow Admins to see all requests (assuming is_admin check in app or specific admin role)
-- For simplicity in this codebase, we often allow public read on some admin tables BUT 
-- logically we should restrict this. 
-- Since we don't have a strict 'admin' role in Supabase auth yet (it's a column in profiles),
-- we will use a policy that checks the profiles table.

DROP POLICY IF EXISTS "Admins can view all verification requests" ON public.verification_requests;
CREATE POLICY "Admins can view all verification requests" 
  ON public.verification_requests FOR SELECT 
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid() AND profiles.is_admin = true
    )
  );

DROP POLICY IF EXISTS "Admins can update verification requests" ON public.verification_requests;
CREATE POLICY "Admins can update verification requests" 
  ON public.verification_requests FOR UPDATE
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid() AND profiles.is_admin = true
    )
  );
